markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
permalink: /:year/:month/:day/:title/
url: http://linchen04.github.com
author: linchen04
highlighter: pygments
safe: true
paginate: 16

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-56284164-1'
  getclicky :
    site_id :
