markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables",     "with_toc_data"]
permalink: /:year/:month/:day/:title/
url: http://linchen04.github.com
author: linchen04
highlighter: pygments
safe: true
paginate: 16
